### ISSUE TITLE
model.py StateMatrixEncoder code logic

### ISSUE THREAD

**Issue by chijames** [LayneIns/E2E-dialo-disentanglement#3]
Hi,

In models.py, ln 169 to ln 174 seems a bit confused to me. Specifically, the "else:" statement in line 173 will never be executed if I understand the logic correctly. Is this a bug or just some dead code to be ignored?

Thanks!

**Comment by LayneIns** [comment]
@chijames Hi, yes it's some dead code and please simply ignore it. I forgot to remove it when reorganizing the code.

**Comment by chijames** [comment]
In addition, in ln 170, sometimes the "position" variable may become -2. This is because state_transition_matrix has the format like:
```
[[[ 0 -1 -1 ... -1 -1 -1]
  [ 0  1 -1 ... -1 -1 -1]
  [ 0  2 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]
```
,
where for those padded utterances, we have rows full of -1.
In this case, we will reach ln 170 with state_transition_matrix[batch_index][i][j] being -1, therefore, position=-2.
I would guess this is not the desired behavior. Please correct me if I am wrong. Thanks!

**Comment by LayneIns** [comment]
@chijames Hi, for the -1 items, it really doesn't matter how you deal with them. You can randomly initialize them because they won't join the final classification (masked). In the code I just use position-1 to initialize it.

**Comment by chijames** [comment]
Right, for those utterances used for padding I believe it will be taken care by the mask. But for those valid utterances, some entries in the state_transition_matrix are still -1 (unused sessions). In other words, they will be appended to one_res in line 172 and participate in the average pooling operation.

**Comment by chijames** [comment]
I think there may be a misunderstanding. So according to paper eq 6, I presume the distribution is calculated only wrt the sessions discovered so far (1 to z(i)). But according to the code, seems like the distribution is calculated wrt all possible sessions (5 sessions) and a softmax layer is applied. Is this correct? If yes, then of course they should all be used for the average pooling operation.

**Comment by LayneIns** [comment]
@chijames Hi, yes you are right. Softmax is applied to all existing sessions during training. While in the inference step, we will mask those session that are not initialized yet.

**Comment by chijames** [comment]
Reopen this issue since I am still a bit confused. We may have state_transition_matrix (one row) like : [ 0  2 -1 ... -1 -1 -1]. This means sessions that are not yet exist also participate in the softmax operation. Moreover, the session representations for those non-existent sessions are session_repre[batch_idx][session_id][-2] according to your code. Is this expected behavior?

**Comment by LayneIns** [comment]
@chijames Hi, sorry for causing the confusion, we have uploaded a new version of code to fix it. As we mentioned before, the initialization method for the unused sessions brings little infect to our method. Thus in this version the unused sessions are all zero-initialized. Hope this can solve your question.
